// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migration.Shipbuilding;

#nullable disable

namespace Migration.Shipbuilding.Migrations
{
    [DbContext(typeof(ShipbuildingDBContext))]
    [Migration("20260629123403_Table EmployeesShipbuilding")]
    partial class TableEmployeesShipbuilding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Migration.Shipbuilding.DTO.EmployeeShipbuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanCarpentry")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDesignShip")
                        .HasColumnType("bit");

                    b.Property<bool>("CanWeld")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EmployeesShipbuilding");
                });
#pragma warning restore 612, 618
        }
    }
}
